#!/bin/bash

version=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' ../package.json)
git_url=''
source_code_dir='ivs-hierarchy'
harbor_url=''
harbor_username=''
harbor_password=''
image_name='harbor.tsl.telus.com/oe-b2b-evs/ivs-hierarchy'

clear

echo "Starting CI shell script...";

read -p "Enter Git branch name (master): " y
y="${y:=master}"
echo "Branch: $y"

read -p "Enter Image Version ($version): " x
x="${x:=$version}"
echo "Version: $x"

rm -rf $source_code_dir

mkdir -p $source_code_dir

cd $source_code_dir

#git clone $git_url
git clone -b $y --single-branch $git_url

cd OE-B2B-EvolveVoiceSvcs-IvsHierarchy

#Create Docker Image and tag as per Telus Harbor standard
docker build -t $image_name:latest -t $image_name:$x .

docker images

#login to Harbor with Robot credentials
docker login $harbor_url --username $harbor_username --password $harbor_password

docker push $image_name:latest 

docker push $image_name:$x

echo "Pushed image to Harbor successfully !!!"

cd ../../
rm -rf $source_code_dir
git tag -a $x -m "Build tag auto generated by OpenShift workflow"
git push origin $x
echo "Ending of the CI shell script ...";
# cat ../../CI-Script.sh