apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }} 
  labels:
    name: {{ .Values.name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3006
      protocol: TCP
      name: web
  selector:
    app: {{ .Values.name }}
